### ISSUE TITLE
پشتیبانی از Xamarin

### ISSUE THREAD

**Issue by ghost1372** [pusheco/pushe#1]
سلام ایا پوشه هیچ برنامه ای‌برای پشتیبانی از پلتفرم زامارین داره؟
من اکثر برنامه هامو با xamarin android و xamarin ios مینویسم

**Comment by akramShokri** [comment]
سلام
ما نسخه ای را برای زامارین آماده کرده ایم که برای اندروید هست ( برای زامارین فرم قابل استفاده نیست). اگر مایل باشید می توانید به پشتیبانی پوشه ایمیلی بزنید تا این نسخه و روش اضافه کردن آن به پروژه برای شما ارسال شود.

**Comment by amiradib** [comment]
سلام

متاسفانه نسخه مربوط به زامارین بسسسسسسسسسسیار ناقص است.
برخلاف onsignal که با Nuget در کسری از دقیقه میشه ران کرد، پوشه اصلا پشتیبانی خوبی نداره
بنده با ایمیل هم مکاتبه کردم و هیچ جوابی دریافت نکردم
چرا نمونه پروژه زامارین رو بر روی Git قرار نمیدید!؟

الان بعد از کلی کلنجار، مشکل من اینه که بعد از اضافه کردن پروژه PusheLib به سلوشنم و  اضافخ کردن رفرنس آن، خطای زیر رو تو پروژه اصلی دریافت میکنم
 The type or namespace name 'PushePlugin' does not exist in the namespace 'CO.Ronash.Pushe' (are you missing an assembly reference?)
